language: node_js
node_js:
  - '8'
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds
script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist:linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:win; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:mac; fi